### ISSUE TITLE
"IndexError: list index out of range" when running Step 4 (pipeline on the genome annotations)

### ISSUE THREAD

**Issue by WDBS369** [DerKevinRiehl/transposon_annotation_reasonaTE#16]
Hi Kevin,

I encounter an error when I ran step4 (pipeline) on my genome annotations. Any idea why this occurred?

Thanks,
Chan

The code I used is:
reasonaTE -mode pipeline -projectFolder Pame.btk.umk.07 -projectName Pame.btk.umk.07

The error info:
![image](https://user-images.githubusercontent.com/45295522/198638717-83e2d04b-26d5-428c-be44-6c7097299771.png)

The process stopped after/at the transposon sequences sorting:
![image](https://user-images.githubusercontent.com/45295522/198642159-a3f4cbc9-eef9-4be5-b80e-18ccfb32cfc0.png)

Also, I checked step 3 (parse tool annotation) and it seems to work fine.
![image](https://user-images.githubusercontent.com/45295522/198649488-16ad4bb9-155d-4ec0-8b6d-1956215f369b.png)

**Comment by DerKevinRiehl** [comment]
Dear Chan Liu,
sorry for the late reply. 

Did you find a solution already?
Otherwise, I think the issue is that for some reason one of your sequence files might be empty.
First of all, thanks for finding this bug, I probably should have added something in the code to deal with it.

To solve it, you need to edit the source code of TransposonClustering.py in python as follows:

From this code
```
    for key in list(clusterData.keys()):
        cluster = clusterData[key]
        transpIDs.append(["transposon"+str(cluster[0]),key])
```

to this code

```
    for key in list(clusterData.keys()):
        cluster = clusterData[key]
        if(len(cluster)!=0):
            transpIDs.append(["transposon"+str(cluster[0]),key])
```

You can find this file in this folder:
/project/xnzh222_uksr/qli259/my_miniconda3/envs/transposon_annotation_resonaTE/share/TransposonAnnotator_reasonaTE/TransposonClustering.py

If you are able to, you could use a linux software like "vim" or "nano" to edit this .py file.

Could this help to solve the issue?
Thanks for letting me know,
Best, Kevin

**Comment by sahoo-rk** [comment]
Hi Kevin,
I find a similar error, but during the mode 'parseAnnotation'. My error message is as follows. Please suggest. Thanks!

Parse must...
Traceback (most recent call last):
  File "/home/sahoork/anaconda3/envs/transposon_annotation_tools_env/share/TransposonAnnotator_reasonaTE/TransposonAnnotator.py", line 114, in <module>
    parseAvailableResults(projectFolderPath)
  File "/home/sahoork/anaconda3/envs/transposon_annotation_tools_env/share/TransposonAnnotator_reasonaTE/AnnotationParser.py", line 1333, in parseAvailableResults
    parseMust(pathResDir, fastaFile, targetGFFFile, targetFastaFile)
  File "/home/sahoork/anaconda3/envs/transposon_annotation_tools_env/share/TransposonAnnotator_reasonaTE/AnnotationParser.py", line 511, in parseMust
    if(transposons[23]=="Full Copy"):
IndexError: list index out of range

best,
