### ISSUE TITLE
Issue with transposon_annotation_reasonaTE

### ISSUE THREAD

**Issue by Ramkyeri** [DerKevinRiehl/transposon_annotation_reasonaTE#23]
Dear Kevin, 
Greetings!
In the follwoing environment;  
conda activate transposon_annotation_reasonaTE
reasonaTE -mode pipeline -projectFolder workspace -projectName testProject

I got the following error:  
workspace/testProject/finalResults/ToolAnnotations_Transposons.gff3 	Traceback (most recent call last):
  File "/home/ram/anaconda3/envs/transposon_annotation_reasonaTE/share/TransposonAnnotator_reasonaTE/TransposonAnnotator.py", line 166, in <module>
    createToolAnnotation_Files(os.path.join(arg1,arg2), os.path.join(arg1,arg2,"finalResults"), os.path.join(arg1,arg2,"parsedAnnotations"), os.path.join(arg1,arg2,"transposonCandB"), os.path.join(arg1,arg2,"transposonCandF"))
  File "/home/ram/anaconda3/envs/transposon_annotation_reasonaTE/share/TransposonAnnotator_reasonaTE/FinalResultsCreator.py", line 78, in createToolAnnotation_Files
    f = open(os.path.join(folderTranspCandF,"ToolAnnotations_TransposonSequencesClasses.txt"),"r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'workspace/testProject/transposonCandF/ToolAnnotations_TransposonSequencesClasses.txt'

please send me your suggestion

with regards 
Ramky

**Comment by Ramkyeri** [comment]
Dear Kevin,  

due to the error which mentionedabove,  I got the got only few files in the FinalResults folder.  

Please send me your suggestion,  I do not know why it is not generated,  ToolAnnotations_TransposonSequencesClasses.txt in TranspCandF. 

<img width="626" alt="image" src="https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/assets/70749594/cef0cee3-eb4d-4c07-97fc-bc003e232a10">


with regards
Ramky

**Comment by Ramkyeri** [comment]
Dear Kevin, 

Based on the error message, 'ToolAnnotations_TransposonSequencesClasses.txt' is not found in the 'transposonCandF' directory.
It was not generated.  I do not know the reason. 
Now what should I do,  

with regards 

Ramky

**Comment by Ramkyeri** [comment]
Dear Kevin, 

It should be text file,  but it is temp file format,   and the output is also different, not like as yours. 
<img width="607" alt="image" src="https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/assets/70749594/c69ef786-dd56-446c-9ba8-724d97553ec7">

<img width="1264" alt="image" src="https://github.com/DerKevinRiehl/transposon_annotation_reasonaTE/assets/70749594/0487077f-18b6-4406-a0a0-46760a5abaeb">
with regards

Ramky

**Comment by Djangodu** [comment]
Dear Ramky

I also running with this protocal of  transposon_annotation_reasonaTE, and got the same Error with you as your present this error, two. Actually, there also have a 'value error' before this ErrNO2, did you notice it?

I just write these two Error Under the TransposonUltimate with the title "Two errors occur while running Step 4, i don't know how it is happened, please help me."https://github.com/DerKevinRiehl/TransposonUltimate/issues/10.

Look forward to Kevin' reply
Sincerely yours

**Comment by Ramkyeri** [comment]
Dear @Djangodu 

Thank you for your message. My errors and your errors are same,   but @DerKevinRiehl  did not reply to the errors. 

With regards 
Ramky
